// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF533ATWldC94acFXYo6Qx6YyQZFFjk6A',
    appId: '1:215211453169:web:65138e19e2273d14051750',
    messagingSenderId: '215211453169',
    projectId: 'video-conference-app-33bf8',
    authDomain: 'video-conference-app-33bf8.firebaseapp.com',
    storageBucket: 'video-conference-app-33bf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XPaIFPWFrYEYI1wz5Xesz5ojIWZZ4S0',
    appId: '1:215211453169:android:78834a12c7b987f7051750',
    messagingSenderId: '215211453169',
    projectId: 'video-conference-app-33bf8',
    storageBucket: 'video-conference-app-33bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHNkRF6nY90sFxNIdjPTxZpzh0IJO-dzQ',
    appId: '1:215211453169:ios:6b826ad38f413a9d051750',
    messagingSenderId: '215211453169',
    projectId: 'video-conference-app-33bf8',
    storageBucket: 'video-conference-app-33bf8.appspot.com',
    iosClientId: '215211453169-fqva9qs7a5hlji7vtjpqjsrb9uoss4cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );
}
